[project]
name = "copywriting"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "moviepy>=2.1.1",
    "pysrt>=1.1.2",
]
